export const GET_EJEMPLO = "GET_EJEMPLO";
export const POST_NFT = "POST_NFT";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SORT_ALFA='SORT_ALFA';
export const FILTER_CATEGORIES='FILTER_CATEGORIES';